### PR TITLE
Release 1.1.7

### PR DESCRIPTION
**Pull request by priley86**
- add latest changes of bootstrap-combobox to our fork

### CODE REVIEW

**Comment by priley86** [comment]
@jeff-phillips-18 are we OK merging this minor update to our fork? I've added this PR to address [PTNFLY-1660](https://patternfly.atlassian.net/browse/PTNFLY-1660)

**Comment by dlabrecq** [comment]
LGTM

**Comment by jeff-phillips-18** [comment]
LGTM, please squash commits

**Comment by priley86** [comment]
@jeff-phillips-18 ready for merge

**Pull request merged**
